#!/bin/bash

cat allSigEstrLabeledTissueTotalBrain-Caudate.txt allSigEstrLabeledTissueTotalBrain-Cerebellum.txt > patternsFiles/allBrainSigEstrLabeledTissueTotalEstr.txt

cat allSigEstrLabeledTissueHipsterBrain-Cerebellum.txt allSigEstrLabeledTissueHipsterBrain-Caudate.txt  > allBrainSigEstrLabeledTissueHipstr.txt
